name: ci

on:
  push:

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/vivid-lapin/mitmproxy
      image-platforms: linux/amd64,linux/arm64/v8
      scan-image: false
      context: .
