name: latest

on:
  push:
  workflow_dispatch:

env:
  DOCKER_BASE_NAME: ghcr.io/vivid-lapin/mitmproxy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ env.DOCKER_BASE_NAME }}:latest
          cache-from: ${{ env.DOCKER_BASE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1
